// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var cell_size, data, render_cell, viewport;
    viewport = $('#griddle');
    data = {
      getItem: function(n) {
        return {
          name: n
        };
      },
      getLength: function() {
        return 1000;
      }
    };
    cell_size = {
      width: 200,
      height: 200
    };
    render_cell = function(item, _arg) {
      var left, top;
      left = _arg.left, top = _arg.top;
      return "<div class=\"cell\" style=\"left:" + left + "px; top:" + top + "px\">\n	" + item.name + "\n</div>";
    };
    window.grid = new SlickGriddle(viewport, data, cell_size, render_cell);
    return $(window).resize(function() {
      return grid.resize();
    });
  });

}).call(this);
